# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OnePush' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!
  
  # pod 'GPUImage', '~> 0.1.7'

  # Pods for OnePush

  pod 'Masonry', '~> 1.1.0'
  
  target 'OnePushTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OnePushUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
